# Site
title: zwj
subtitle: ''
description: 'zwj blog'
keywords:
author: zwj
language: en
timezone: ''

# Build settings
theme: minima

nav:
- name: Home
  link: /
- name: About
  link: /about.html


